"""Generate JSON schema and docs reference for prepmd config."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, cast

from prepmd.config.models import ProjectConfig


def build_project_schema() -> dict[str, Any]:
    """Build JSON schema for :class:`prepmd.config.models.ProjectConfig`."""
    schema = ProjectConfig.model_json_schema()
    schema["title"] = "ProjectConfig"
    return schema


def canonical_schema_json(schema: dict[str, Any]) -> str:
    """Render deterministic JSON text for schema output."""
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def _field_type(metadata: dict[str, Any]) -> str:
    if "type" in metadata:
        return str(metadata["type"])
    if "$ref" in metadata:
        return str(metadata["$ref"]).split("/")[-1]
    if "enum" in metadata:
        return "enum"
    any_of_raw = metadata.get("anyOf", [])
    if isinstance(any_of_raw, list):
        type_parts: list[str] = []
        for part in cast(list[object], any_of_raw):
            if not isinstance(part, dict):
                continue
            part_dict = cast(dict[str, object], part)
            part_type = part_dict.get("type")
            if part_type is not None:
                type_parts.append(str(part_type))
                continue
            part_ref = part_dict.get("$ref")
            if part_ref is not None:
                type_parts.append(str(part_ref).split("/")[-1])
        if type_parts:
            return " | ".join(type_parts)
    return "object"


def _required_text(*, required: bool) -> str:
    return "yes" if required else "no"


def schema_to_reference_rst(schema: dict[str, Any]) -> str:
    """Render a simple config reference page from JSON schema content."""
    lines = [
        "Config reference",
        "================",
        "",
        "This page is autogenerated from the ``ProjectConfig`` JSON Schema.",
        "",
        ".. list-table:: Top-level fields",
        "   :header-rows: 1",
        "",
        "   * - Field",
        "     - Type",
        "     - Required",
        "     - Default",
        "     - Description",
    ]
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    for name, metadata in properties.items():
        field_type = _field_type(metadata)
        default = metadata.get("default", "")
        description = metadata.get("description", "")
        lines.extend(
            [
                f"   * - ``{name}``",
                f"     - ``{field_type}``",
                f"     - {_required_text(required=name in required)}",
                f"     - ``{default}``" if default != "" else "     - ",
                f"     - {description}",
            ]
        )

    defs = schema.get("$defs", {})
    if defs:
        lines.extend(["", "Nested models", "-------------", ""])
    for model_name in sorted(defs):
        model = defs[model_name]
        lines.extend([model_name, "~" * len(model_name), ""])
        model_properties = model.get("properties", {})
        if not model_properties:
            enum_values = model.get("enum", [])
            if enum_values:
                lines.append(f"Allowed values: ``{', '.join(str(v) for v in enum_values)}``")
                lines.append("")
            continue
        lines.extend(
            [
                ".. list-table::",
                "   :header-rows: 1",
                "",
                "   * - Field",
                "     - Type",
                "     - Required",
                "     - Default",
                "     - Description",
            ]
        )
        model_required = set(model.get("required", []))
        for field_name, metadata in model_properties.items():
            field_type = _field_type(metadata)
            default = metadata.get("default", "")
            description = metadata.get("description", "")
            lines.extend(
                [
                    f"   * - ``{field_name}``",
                    f"     - ``{field_type}``",
                    f"     - {_required_text(required=field_name in model_required)}",
                    f"     - ``{default}``" if default != "" else "     - ",
                    f"     - {description}",
                ]
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_schema(path: Path) -> None:
    """Write project schema JSON to ``path``."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(canonical_schema_json(build_project_schema()), encoding="utf-8")


def write_reference(path: Path, *, schema: dict[str, Any] | None = None) -> None:
    """Write autogenerated config reference RST to ``path``."""
    payload = schema if schema is not None else build_project_schema()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(schema_to_reference_rst(payload), encoding="utf-8")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate prepmd config schema")
    parser.add_argument("--output", "-o", type=Path, help="Write JSON schema to a path (stdout if omitted).")
    parser.add_argument("--reference-rst", type=Path, help="Write autogenerated config reference RST to a path.")
    return parser.parse_args()


def main() -> None:
    """CLI entrypoint for schema/reference generation."""
    args = _parse_args()
    schema = build_project_schema()
    if args.output is None:
        print(canonical_schema_json(schema), end="")
    else:
        write_schema(args.output)
    if args.reference_rst is not None:
        write_reference(args.reference_rst, schema=schema)


if __name__ == "__main__":
    main()
